### ISSUE TITLE
Can't override TCPDF's config

### ISSUE THREAD

**Issue by mcapinha-mxp** [Qipsius/QipsiusTCPDFBundle#1]
Hi all,

We're seeing the same issue that's referenced here: https://github.com/sampart/WhiteOctoberTCPDFBundle/issues/29 

In a nutshell, we define our `k_path_images` in `services.yml` but it ends up being ignored in QipsiusTCPDFBundle::boot() as K_PATH_IMAGES as already been defined. That in turn happens because tcpdf.php requires tcpdf_autoconfig.php, which ends up defining K_PATH_IMAGES.

Any hints please? :)

**Comment by davnavarro** [comment]
Hi,
Reviewing projects where we use this library, I see that we define the path from the root directory in each situation:
```
src="/assets/img/example1.png"
src="/assets/images/example2.png"
```

I know it is not the answer to what you need, but we maintain this library so that it can be used in versions greater than 4 of symfony, we have not developed it and it is not our goal to improve it, sorry
